\c medicinow_api;

DROP TABLE IF EXISTS APPOINTMENTS ;

DROP TABLE IF EXISTS DOCTORS_DATA;

DROP TABLE IF EXISTS DOCTORS ;

DROP TABLE IF EXISTS OFFICES ;

DROP TABLE IF EXISTS PACIENTS;

DROP TABLE IF EXISTS MEDICAL_AGREEMENTS;

CREATE TABLE IF NOT EXISTS MEDICAL_AGREEMENTS (
medical_agreement_id SERIAL PRIMARY KEY,
brand VARCHAR NOT NULL ,
plan VARCHAR(18) NOT NULL,
UNIQUE (brand, plan),
created_at TIMESTAMP DEFAULT current_timestamp,
updated_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE PACIENTS (
pacient_id SERIAL PRIMARY KEY,
last_name VARCHAR NOT NULL,
first_name VARCHAR NOT NULL,
email VARCHAR UNIQUE,
password VARCHAR NOT NULL,
telephone VARCHAR,
card_number VARCHAR,
medical_agreement_id BIGINT REFERENCES MEDICAL_AGREEMENTS ON DELETE RESTRICT,
created_at TIMESTAMP DEFAULT current_timestamp,
updated_at TIMESTAMP DEFAULT current_timestamp
);

CREATE  TABLE IF NOT EXISTS OFFICES (
office_id SERIAL PRIMARY KEY,
name VARCHAR,
street_address VARCHAR,
created_at TIMESTAMP DEFAULT current_timestamp,
updated_at TIMESTAMP DEFAULT current_timestamp
);


CREATE TABLE IF NOT EXISTS DOCTORS (
doctor_id SERIAL PRIMARY KEY,
last_name VARCHAR NOT NULL,
first_name VARCHAR NOT NULL,
email VARCHAR UNIQUE NOT NULL,
password VARCHAR NOT NULL,
speciality VARCHAR ,
crm VARCHAR(13) UNIQUE,
appointment_price NUMERIC(10,2),
telephone NUMERIC (11),
created_at TIMESTAMP DEFAULT current_timestamp,
updated_at TIMESTAMP DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS DOCTORS_DATA (
doctor_id BIGINT UNIQUE REFERENCES DOCTORS(doctor_id)  ON DELETE RESTRICT,
office_id BIGINT UNIQUE REFERENCES OFFICES(office_id)  ON DELETE RESTRICT,
medical_agreement_id BIGINT UNIQUE REFERENCES MEDICAL_AGREEMENTS(medical_agreement_id) ON DELETE RESTRICT,
PRIMARY KEY(doctor_id, office_id, medical_agreement_id)
);

CREATE TABLE IF NOT EXISTS APPOINTMENTS (
appointment_id SERIAL PRIMARY KEY,
pacient_id BIGINT REFERENCES PACIENTS(pacient_id) ON DELETE RESTRICT,
doctor_id BIGINT REFERENCES DOCTORS_DATA(doctor_id) ON DELETE RESTRICT,
office_id BIGINT REFERENCES DOCTORS_DATA(office_id) ON DELETE RESTRICT,
medical_agreement_id BIGINT REFERENCES DOCTORS_DATA(medical_agreement_id) ON DELETE RESTRICT,
appointment_day DATE NOT NULL,
appointment_hour TIME NOT NULL,
UNIQUE(appointment_day, appointment_hour),
confirmed BOOLEAN DEFAULT true,
canceled BOOLEAN DEFAULT false,
created_at TIMESTAMP DEFAULT current_timestamp,
updated_at TIMESTAMP DEFAULT current_timestamp
);
