ALTER TABLE PACIENTS
  RENAME COLUMN id TO pacient_id;

ALTER TABLE MEDICAL_AGREEMENTS
  RENAME COLUMN id TO medical_agreement_id;

ALTER TABLE OFFICES
  RENAME COLUMN id TO office_id;

ALTER TABLE APPOINTMENTS
  RENAME COLUMN id TO appointment_id;

CREATE TABLE DOCTORS_OFFICES(
doctor_id BIGINT REFERENCES DOCTORS(doctor_id) ON DELETE RESTRICT,
office_id BIGINT REFERENCES OFFICE(office_id) ON DELETE RESTRICT,
PRIMARY KEY (doctor_id, office_id)
);

ALTER TABLE APPOINTMENTS
  DROP CONSTRAINT appointments_pk,
  ADD COLUMN office_id BIGINT REFERENCES OFFICE(office_id) ON DELETE RESTRICT,
  ADD CONSTRAINT appointments_pk
    PRIMARY KEY (pacient_id, doctor_id, office_id);
