ALTER TABLE PACIENTS
  DROP COLUMN IF EXISTS gender,
  DROP COLUMN IF EXISTS age,
  DROP COLUMN IF EXISTS street_address,
  DROP COLUMN IF EXISTS cpf,
  DROP COLUMN IF EXISTS rg,
  DROP COLUMN IF EXISTS card_number,
  ADD COLUMN telephone NUMERIC(10);

ALTER TABLE DOCTORS
  DROP COLUMN IF EXISTS gender,
  DROP COLUMN IF EXISTS age,
  ALTER COLUMN crm TYPE VARCHAR(13),
  ALTER COLUMN appointment_value DROP NOT NULL,
  ADD COLUMN telephone NUMERIC(10);
